### ISSUE TITLE
About the demo of multi_class GNN with K labels?

### ISSUE THREAD

**Issue by goes0n** [Analystharsh/GCN_complex_detection#1]
Is there any demo which integrates multi_class GNN with K labels and mean-shift clustering, as shown in Table 2 in paper?
![image](https://user-images.githubusercontent.com/39076695/178674260-1942e78b-7bbc-47f2-a7c3-7a6623e41efa.png)

**Comment by hars-singh** [comment]
Files: Human_Feature_Generation_and_results.ipynb and Mouse_Feature_Generation_and_results.ipynb
